// swift-tools-version: 6.1

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
// No AppleProductTypes import

let package = Package(
    name: "Buddy",
    platforms: [
        .macOS(.v15), // Executable can run on macOS, add platform for SwiftUI
        .iOS("17.0")
    ],
    products: [
        // Define a standard executable product
        .executable(name: "Buddy", targets: ["Buddy"])
    ],
    targets: [
        .executableTarget(
            name: "Buddy",
            path: ".",
            // Exclude common directories from the build target
            exclude: ["docs", ".git", ".gitignore", ".build", ".vscode", ".swiftpm", "README.md"],
            sources: ["Sources"], // Explicitly specify source directory
            resources: [ // Add this resources block
                .copy("Resources")
            ]
        )
    ]
)